app = "vencura"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"
  [build.args]
    VITE_DYNAMIC_ENVIRONMENT_ID = "bf348ffc-a3b0-4840-84ea-8d2635da1a88"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1